name: heisenberg_qiskit_py37
channels:
  - defaults
dependencies:
  - pip=20.3
  - pylint=2.6
  - python=3.7.9
  - pip:
    - cloudant==2.14
    - numpy==1.19.4
    - pandas==1.1.4
    - qiskit==0.23.1
    - qiskit-aer==0.7.1
    - qiskit-aqua==0.8.1
    - qiskit-ibmq-provider==0.11.1
    - qiskit-ignis==0.5.1
    - qiskit-terra==0.16.1
    - scikit-learn==0.23.2
    - scipy==1.5.4
